# -*- coding: utf-8 -*-
from . import student
from . import student_delete_wizard
from . import student_id_history
from . import change_program_wizard
from . import student_field_security
from . import student_care
from . import school_class
from . import course_catalog
from . import program_requirement
from . import enrollment
from . import admission
from . import admission_document_review
from . import admission_website
from . import admission_reference_mail
from . import admission_reference_request
from . import grade
from . import attendance
from . import teacher
from . import registrar
from . import announcement
from . import fee
from . import product_template
from . import razorpay_payment
from . import canvas_api
from . import canvas_term
from . import canvas_sync_issue
from . import canvas_sync
from . import mail_mail
from . import mail_template
from . import res_config_settings
from . import res_partner
from . import res_users
from . import ir_config_parameter
from . import ir_access_messages